version: '3.10.2'

services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000 && daphne minichat.asgi:application"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=minichat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=minichat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: